import type { ImageryProvider } from "@/types/imagery";
import { GibsProvider } from "./GibsProvider";
import { SentinelProvider } from "./SentinelProvider";

const gibsProviders: ImageryProvider[] = [
  new GibsProvider({
    id: "modis-terra",
    layerId: "MODIS_Terra_CorrectedReflectance_TrueColor",
    name: "MODIS Terra",
    satellite: "Terra",
    category: "True color",
    resolution: 250,
    summary: "Morning-pass MODIS true-color imagery, roughly what human eyes would see from orbit.",
    bestFor: "Long-running archive, cloud patterns, smoke, snow, broad land and ocean context.",
    caveat: "Moderate resolution only; city-scale zooms will soften quickly.",
  }),
  new GibsProvider({
    id: "modis-aqua",
    layerId: "MODIS_Aqua_CorrectedReflectance_TrueColor",
    name: "MODIS Aqua",
    satellite: "Aqua",
    category: "True color",
    resolution: 250,
    summary: "Afternoon-pass MODIS true-color imagery that complements Terra's morning view.",
    bestFor: "Comparing same-day cloud cover and lighting against Terra.",
    caveat: "Same moderate-resolution tradeoff as Terra; often cloud-limited.",
  }),
  new GibsProvider({
    id: "viirs-snpp",
    layerId: "VIIRS_SNPP_CorrectedReflectance_TrueColor",
    name: "VIIRS SNPP",
    satellite: "Suomi NPP",
    category: "True color",
    resolution: 375,
    summary: "Modern VIIRS true-color imagery from Suomi NPP with daily global coverage.",
    bestFor: "Recent broad-area imagery, storms, wildfire smoke, snow, sea ice, and land/ocean context.",
    caveat: "Nominal resolution is coarser than MODIS, but coverage and recency are strong.",
  }),
  new GibsProvider({
    id: "viirs-noaa20",
    layerId: "VIIRS_NOAA20_CorrectedReflectance_TrueColor",
    name: "VIIRS NOAA-20",
    satellite: "NOAA-20",
    category: "True color",
    resolution: 375,
    summary: "Alternate VIIRS true-color view from NOAA-20.",
    bestFor: "Another daily pass when SNPP is cloudy, late, or visually less useful.",
    caveat: "Still moderate-resolution and not building- or street-level.",
  }),
  new GibsProvider({
    id: "viirs-snpp-swir",
    layerId: "VIIRS_SNPP_CorrectedReflectance_BandsM11-I2-I1",
    name: "VIIRS SNPP SWIR",
    satellite: "Suomi NPP",
    category: "False color",
    resolution: 375,
    summary: "Shortwave-infrared false color that makes burn scars and some smoke/cloud differences easier to read.",
    bestFor: "Wildfires, burn scars, flooded areas, snow/ice/cloud separation, and vegetation contrast.",
    caveat: "Colors are analytic rather than natural; it can look strange until you learn the palette.",
  }),
  new GibsProvider({
    id: "viirs-snpp-cloud-snow",
    layerId: "VIIRS_SNPP_CorrectedReflectance_BandsM3-I3-M11",
    name: "VIIRS SNPP Cloud/Snow",
    satellite: "Suomi NPP",
    category: "False color",
    resolution: 375,
    summary: "Visible, near-infrared, and shortwave-infrared composite tuned for cloud, snow, ice, and land-surface contrast.",
    bestFor: "Separating snow or ice from clouds and seeing water/vegetation differences.",
    caveat: "Best interpreted comparatively; it is not meant to look photographic.",
  }),
  new GibsProvider({
    id: "viirs-noaa20-swir",
    layerId: "VIIRS_NOAA20_CorrectedReflectance_BandsM11-I2-I1",
    name: "VIIRS NOAA-20 SWIR",
    satellite: "NOAA-20",
    category: "False color",
    resolution: 375,
    summary: "NOAA-20 shortwave-infrared false color, useful as an alternate pass to SNPP.",
    bestFor: "Fire, burn scar, flood, snow, ice, and vegetation contrast on another VIIRS platform.",
    caveat: "False-color interpretation takes a moment; this is analysis imagery, not natural color.",
  }),
  new GibsProvider({
    id: "viirs-black-marble",
    layerId: "VIIRS_Black_Marble",
    name: "VIIRS Black Marble",
    satellite: "Suomi NPP / NOAA-20",
    category: "Night lights",
    resolution: 500,
    fixedDate: "2016-01-01",
    summary: "Annual VIIRS Day/Night Band composite of Earth at night, the classic Black Marble image.",
    bestFor: "Urban footprint, infrastructure, fishing fleets, and identifying cities or power outages.",
    caveat: "Annual snapshot pinned to 2016; bright moonlight and snow can brighten otherwise dark areas.",
  }),
  new GibsProvider({
    id: "modis-aod",
    layerId: "MODIS_Combined_Value_Added_AOD",
    name: "MODIS Aerosol Optical Depth",
    satellite: "Terra + Aqua MODIS",
    category: "Aerosol",
    resolution: 10000,
    overlayOnly: true,
    summary: "Combined Terra and Aqua daily AOD, highlighting wildfire smoke, dust, and pollution plumes.",
    bestFor: "Smoke plume tracking, dust storms, urban haze, and aerosols that are invisible in true color.",
    caveat: "Coarse ~10 km grid; retrieved only over cloud-free pixels and reliable land/ocean surfaces.",
  }),
  new GibsProvider({
    id: "modis-cloud-top-temp",
    layerId: "MODIS_Terra_Cloud_Top_Temp_Day",
    name: "MODIS Cloud Top Temperature",
    satellite: "Terra MODIS",
    category: "Atmosphere",
    resolution: 5000,
    overlayOnly: true,
    summary: "Daytime cloud top temperature from Terra MODIS; colder tops are higher and usually more energetic.",
    bestFor: "Storm structure, thunderstorm tops, hurricane eye contrast, and convective intensity.",
    caveat: "Daytime passes only; cloud-free pixels and the underlying surface are masked out.",
  }),
  new GibsProvider({
    id: "amsr2-precipitable-water",
    layerId: "AMSRU2_Total_Precipitable_Water_Day",
    name: "AMSR2 Precipitable Water",
    satellite: "GCOM-W AMSR2",
    category: "Atmosphere",
    resolution: 25000,
    overlayOnly: true,
    fixedDate: "2025-09-01",
    summary: "Total column water vapor from the AMSR2 daytime ascending pass.",
    bestFor: "Atmospheric river tracking, moisture flow into storms, and tropical-extratropical exchange.",
    caveat: "GIBS archive currently ends 2025-09-01. Ocean-only retrieval at ~25 km.",
  }),
  new GibsProvider({
    id: "ghrsst-sst",
    layerId: "GHRSST_L4_MUR_Sea_Surface_Temperature",
    name: "GHRSST Sea Surface Temperature",
    satellite: "GHRSST MUR L4",
    category: "Sea surface",
    resolution: 1000,
    overlayOnly: true,
    summary: "Daily MUR L4 ultra-high-resolution SST blending microwave and infrared sensors.",
    bestFor: "Ocean currents, eddies, El Niño signatures, hurricane fuel, and coastal upwelling.",
    caveat: "Gridded at 1 km but underlying sensors are coarser; coastline pixels can be noisy.",
  }),
  new GibsProvider({
    id: "modis-chlorophyll",
    layerId: "MODIS_Aqua_L2_Chlorophyll_A",
    name: "MODIS Chlorophyll-a",
    satellite: "Aqua MODIS",
    category: "Ocean color",
    resolution: 1000,
    overlayOnly: true,
    summary: "Surface chlorophyll-a concentration from Aqua MODIS, marking phytoplankton blooms.",
    bestFor: "Bloom tracking, ocean productivity, river plumes, and seasonal ocean ecology.",
    caveat: "Cloud-limited and noisy near land; bright values can also be sediment rather than phytoplankton.",
  }),
  new GibsProvider({
    id: "modis-snow-cover",
    layerId: "MODIS_Terra_NDSI_Snow_Cover",
    name: "MODIS Snow Cover (NDSI)",
    satellite: "Terra MODIS",
    category: "Cryosphere",
    resolution: 500,
    overlayOnly: true,
    summary: "Daily NDSI-based snow cover fraction from Terra MODIS at 500 m.",
    bestFor: "Seasonal snowpack, snow-line shifts, and ski-region or watershed monitoring.",
    caveat: "Misclassifies under thick clouds; tiles in polar darkness are unavailable.",
  }),
  new GibsProvider({
    id: "amsr2-sea-ice",
    layerId: "AMSRU2_Sea_Ice_Concentration_12km",
    name: "AMSR2 Sea Ice Concentration",
    satellite: "GCOM-W AMSR2",
    category: "Cryosphere",
    resolution: 12000,
    overlayOnly: true,
    fixedDate: "2025-09-01",
    summary: "Daily 12 km sea ice concentration from the AMSR2 microwave sensor.",
    bestFor: "Polar ice extent, summer/winter ice tracking, and Arctic shipping context.",
    caveat: "GIBS archive currently ends 2025-09-01. Coarse 12 km grid; melt ponds drop apparent concentration.",
  }),
  new GibsProvider({
    id: "viirs-noaa20-fires",
    layerId: "VIIRS_NOAA20_Thermal_Anomalies_375m_Day",
    name: "VIIRS Active Fires",
    satellite: "NOAA-20 VIIRS",
    category: "Fires",
    resolution: 375,
    overlayOnly: true,
    summary: "Daytime VIIRS thermal anomaly detections at 375 m, marking active fires and hot spots.",
    bestFor: "Wildfire fronts, industrial flares, and lava — pair as an overlay on a true-color base.",
    caveat: "Point detections only; sparse alone — designed to be used as a translucent overlay.",
  }),
  new GibsProvider({
    id: "modis-fires",
    layerId: "MODIS_Combined_Thermal_Anomalies_All",
    name: "MODIS Active Fires",
    satellite: "Terra + Aqua MODIS",
    category: "Fires",
    resolution: 1000,
    overlayOnly: true,
    summary: "Combined Terra + Aqua MODIS thermal anomaly detections across day and night passes.",
    bestFor: "Long archive of active fire locations going back to the early 2000s.",
    caveat: "Coarser than VIIRS fires; sparse alone — use as a translucent overlay.",
  }),
];

// Sentinel imagery needs Copernicus server credentials, so it is hidden by
// default. The free NASA-only build never offers a layer it can't load. To turn
// it on, build with VITE_ENABLE_SENTINEL=true AND set the Copernicus keys on the
// server (see .env.example).
const SENTINEL_ENABLED = import.meta.env.VITE_ENABLE_SENTINEL === "true";

const sentinelProviders: ImageryProvider[] = SENTINEL_ENABLED
  ? [
      new SentinelProvider({ id: "sentinel-2-true-color", variantId: "s2-true-color" }),
      new SentinelProvider({ id: "sentinel-2-false-color", variantId: "s2-false-color" }),
      new SentinelProvider({ id: "sentinel-2-swir", variantId: "s2-swir" }),
      new SentinelProvider({ id: "sentinel-1-radar", variantId: "s1-radar" }),
    ]
  : [];

export const imageryProviders: ImageryProvider[] = [...gibsProviders, ...sentinelProviders];

export const modalImageryProviders = [
  ...imageryProviders.filter((provider) => provider.sentinelVariantId),
  ...imageryProviders.filter((provider) => !provider.sentinelVariantId && !provider.overlayOnly),
];

const imageryProviderById = new Map(imageryProviders.map((provider) => [provider.id, provider]));

export function getImageryProvider(id: string) {
  return imageryProviderById.get(id) ?? imageryProviders[0];
}
